# Repotoire GitHub App Manifest
# https://docs.github.com/en/apps/sharing-github-apps/registering-a-github-app-from-a-manifest
#
# This manifest defines the Repotoire GitHub App for automated code analysis.
# Use this to register the app at: https://github.com/settings/apps/new?manifest=...

name: Repotoire
description: AI-powered code analysis with real-time PR feedback and security scanning
url: https://repotoire.dev
hook_attributes:
  url: https://api.repotoire.dev/webhooks/github
  active: true

# Redirect after app installation
redirect_url: https://repotoire.dev/github/callback
setup_url: https://repotoire.dev/github/setup
setup_on_update: true

# Run as a GitHub App (not OAuth)
public: true

# Default events to subscribe to
default_events:
  - check_run
  - check_suite
  - pull_request
  - push
  - repository

# Default permissions
default_permissions:
  # Required for setting commit statuses (pending/success/failure)
  statuses: write
  
  # Required for posting PR comments with analysis results
  pull_requests: write
  
  # Required for uploading SARIF code scanning results
  security_events: write
  
  # Required for reading repository contents for analysis
  contents: read
  
  # Required for check runs (detailed PR status with annotations)
  checks: write
  
  # Required for reading repository metadata
  metadata: read

# Callback URL for OAuth flow (if using user authorization)
callback_urls:
  - https://repotoire.dev/auth/github/callback
