name: 'Repotoire Code Quality Check'
description: 'Analyze code quality and post findings to PR comments'
author: 'Repotoire Team'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  fail-on:
    description: 'Minimum severity level to fail the check (critical, high, medium, low)'
    required: false
    default: 'critical'

  comment-on-pr:
    description: 'Post findings as PR comment'
    required: false
    default: 'true'

  incremental:
    description: 'Use incremental analysis (only changed files)'
    required: false
    default: 'true'

  neo4j-uri:
    description: 'Neo4j connection URI'
    required: false
    default: 'bolt://localhost:7687'

  neo4j-password:
    description: 'Neo4j password (use secrets for this)'
    required: true

  github-token:
    description: 'GitHub token for PR comments (defaults to GITHUB_TOKEN)'
    required: false
    default: ${{ github.token }}

  python-version:
    description: 'Python version to use'
    required: false
    default: '3.10'

outputs:
  findings-count:
    description: 'Total number of findings'
    value: ${{ steps.analyze.outputs.findings-count }}

  critical-count:
    description: 'Number of critical findings'
    value: ${{ steps.analyze.outputs.critical-count }}

  health-score:
    description: 'Overall health score (0-100)'
    value: ${{ steps.analyze.outputs.health-score }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install Repotoire
      shell: bash
      run: |
        uv pip install -e "${{ github.action_path }}/../../.."

    - name: Get changed files
      id: changed-files
      shell: bash
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "files=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }} | grep '\.py$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
        else
          echo "files=$(git diff --name-only HEAD~1 | grep '\.py$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
        fi

    - name: Run Repotoire Analysis
      id: analyze
      shell: bash
      env:
        REPOTOIRE_NEO4J_URI: ${{ inputs.neo4j-uri }}
        REPOTOIRE_NEO4J_PASSWORD: ${{ inputs.neo4j-password }}
      run: |
        ${{ github.action_path }}/run-analysis.sh \
          --fail-on "${{ inputs.fail-on }}" \
          --incremental "${{ inputs.incremental }}" \
          --files "${{ steps.changed-files.outputs.files }}"

    - name: Post PR Comment
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const fs = require('fs');
          const comment = fs.readFileSync('${{ github.workspace }}/.repotoire/pr-comment.md', 'utf8');

          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(comment =>
            comment.user.type === 'Bot' &&
            comment.body.includes('🤖 Repotoire Code Quality Report')
          );

          if (botComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: comment
            });
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
          }
