name: 'Repotoire PR Check'
description: 'Run Repotoire code analysis on pull requests'
author: 'Repotoire'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  severity:
    description: 'Minimum severity to report (info, low, medium, high, critical)'
    required: false
    default: 'medium'
  fail-on:
    description: 'Fail the check if issues at this severity or above are found'
    required: false
    default: 'high'
  changed-only:
    description: 'Only analyze changed files in the PR'
    required: false
    default: 'true'
  token:
    description: 'GitHub token for posting PR comments'
    required: false
    default: ${{ github.token }}
  openai-key:
    description: 'OpenAI API key for AI-powered suggestions (optional)'
    required: false
  anthropic-key:
    description: 'Anthropic API key for AI-powered suggestions (optional)'
    required: false

outputs:
  findings-count:
    description: 'Total number of findings'
    value: ${{ steps.analyze.outputs.findings-count }}
  critical-count:
    description: 'Number of critical findings'
    value: ${{ steps.analyze.outputs.critical-count }}
  high-count:
    description: 'Number of high severity findings'
    value: ${{ steps.analyze.outputs.high-count }}
  grade:
    description: 'Overall code health grade (A-F)'
    value: ${{ steps.analyze.outputs.grade }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Repotoire
      shell: bash
      run: |
        pip install repotoire --quiet
        repotoire --version

    - name: Run analysis
      id: analyze
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai-key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-key }}
      run: |
        # Build analyze command
        # Use --changed to analyze only files changed in PR
        if [ "${{ inputs.changed-only }}" == "true" ] && [ "${{ github.event_name }}" == "pull_request" ]; then
          ANALYZE_CMD="repotoire analyze . --severity ${{ inputs.severity }} --changed ${{ github.event.pull_request.base.sha }} -f json -o .repotoire/findings.json"
        else
          ANALYZE_CMD="repotoire analyze . --severity ${{ inputs.severity }} -f json -o .repotoire/findings.json"
        fi
        
        echo "Running: $ANALYZE_CMD"
        eval $ANALYZE_CMD || true
        
        # Parse results
        if [ -f .repotoire/findings.json ]; then
          FINDINGS=$(cat .repotoire/findings.json)
          TOTAL=$(echo "$FINDINGS" | jq 'length')
          CRITICAL=$(echo "$FINDINGS" | jq '[.[] | select(.severity == "critical")] | length')
          HIGH=$(echo "$FINDINGS" | jq '[.[] | select(.severity == "high")] | length')
          MEDIUM=$(echo "$FINDINGS" | jq '[.[] | select(.severity == "medium")] | length')
          LOW=$(echo "$FINDINGS" | jq '[.[] | select(.severity == "low")] | length')
        else
          TOTAL=0
          CRITICAL=0
          HIGH=0
          MEDIUM=0
          LOW=0
        fi
        
        # Get grade from health report
        if [ -f .repotoire/last_health.json ]; then
          GRADE=$(cat .repotoire/last_health.json | jq -r '.grade // "N/A"')
        else
          GRADE="N/A"
        fi
        
        echo "findings-count=$TOTAL" >> $GITHUB_OUTPUT
        echo "critical-count=$CRITICAL" >> $GITHUB_OUTPUT
        echo "high-count=$HIGH" >> $GITHUB_OUTPUT
        echo "medium-count=$MEDIUM" >> $GITHUB_OUTPUT
        echo "low-count=$LOW" >> $GITHUB_OUTPUT
        echo "grade=$GRADE" >> $GITHUB_OUTPUT

    - name: Post PR comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        FINDINGS_COUNT: ${{ steps.analyze.outputs.findings-count }}
        CRITICAL_COUNT: ${{ steps.analyze.outputs.critical-count }}
        HIGH_COUNT: ${{ steps.analyze.outputs.high-count }}
        MEDIUM_COUNT: ${{ steps.analyze.outputs.medium-count }}
        LOW_COUNT: ${{ steps.analyze.outputs.low-count }}
        GRADE: ${{ steps.analyze.outputs.grade }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const fs = require('fs');
          
          const total = parseInt(process.env.FINDINGS_COUNT) || 0;
          const critical = parseInt(process.env.CRITICAL_COUNT) || 0;
          const high = parseInt(process.env.HIGH_COUNT) || 0;
          const medium = parseInt(process.env.MEDIUM_COUNT) || 0;
          const low = parseInt(process.env.LOW_COUNT) || 0;
          const grade = process.env.GRADE || 'N/A';
          
          // Build status emoji
          let statusEmoji = '✅';
          if (critical > 0) statusEmoji = '🚨';
          else if (high > 0) statusEmoji = '⚠️';
          else if (medium > 0) statusEmoji = '📋';
          
          // Build findings table
          let findingsTable = '';
          if (fs.existsSync('.repotoire/findings.json')) {
            try {
              const findings = JSON.parse(fs.readFileSync('.repotoire/findings.json', 'utf8'));
              if (findings.length > 0) {
                findingsTable = '\n\n<details>\n<summary>📋 Top Findings</summary>\n\n';
                findingsTable += '| Severity | Issue | File | Line |\n';
                findingsTable += '|----------|-------|------|------|\n';
                
                const topFindings = findings.slice(0, 10);
                for (const f of topFindings) {
                  const severity = f.severity === 'critical' ? '🔴' : 
                                   f.severity === 'high' ? '🟠' : 
                                   f.severity === 'medium' ? '🟡' : '🟢';
                  const file = f.file_path || f.path || 'N/A';
                  const line = f.line_start || f.line || '-';
                  const issue = (f.title || f.message || 'Issue').substring(0, 60);
                  findingsTable += `| ${severity} ${f.severity} | ${issue} | \`${file}\` | ${line} |\n`;
                }
                
                if (findings.length > 10) {
                  findingsTable += `\n*...and ${findings.length - 10} more*\n`;
                }
                findingsTable += '\n</details>';
              }
            } catch (e) {
              console.log('Could not parse findings:', e);
            }
          }
          
          const body = `## ${statusEmoji} Repotoire Analysis

          **Grade:** ${grade} | **Findings:** ${total}

          | Severity | Count |
          |----------|-------|
          | 🔴 Critical | ${critical} |
          | 🟠 High | ${high} |
          | 🟡 Medium | ${medium} |
          | 🟢 Low | ${low} |
          ${findingsTable}

          ---
          <sub>Powered by [Repotoire](https://repotoire.com) · [View full report](https://repotoire.com/cli)</sub>`;
          
          // Find existing comment
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          
          const botComment = comments.find(c => 
            c.user.type === 'Bot' && c.body.includes('Repotoire Analysis')
          );
          
          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }

    - name: Check threshold
      shell: bash
      run: |
        CRITICAL=${{ steps.analyze.outputs.critical-count }}
        HIGH=${{ steps.analyze.outputs.high-count }}
        FAIL_ON="${{ inputs.fail-on }}"
        
        if [ "$FAIL_ON" == "critical" ] && [ "$CRITICAL" -gt 0 ]; then
          echo "❌ Found $CRITICAL critical issue(s)"
          exit 1
        fi
        
        if [ "$FAIL_ON" == "high" ]; then
          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "❌ Found $CRITICAL critical and $HIGH high severity issue(s)"
            exit 1
          fi
        fi
        
        echo "✅ No blocking issues found"
