// This file is generated by scripts/product_facts.py. Do not edit by hand.
export const PRODUCT_FACTS = {
  "detectors": {
    "default": 77,
    "deep_scan": 33,
    "total": 110
  },
  "languages": {
    "full_graph": [
      "Python",
      "TypeScript",
      "JavaScript",
      "Rust",
      "Go",
      "Java",
      "C#",
      "C",
      "C++"
    ],
    "full_graph_count": 9,
    "regex_scanned": [
      "Ruby",
      "PHP",
      "Kotlin",
      "Swift"
    ],
    "regex_scanned_count": 4,
    "total_supported_count": 13
  },
  "messaging": {
    "headline_detector_count": 110,
    "headline_language_count": 9,
    "headline_language_label": "graph-native languages"
  }
} as const;

export const FULL_GRAPH_LANGUAGE_LIST = PRODUCT_FACTS.languages.full_graph.join(', ');
export const REGEX_SCANNED_LANGUAGE_LIST = PRODUCT_FACTS.languages.regex_scanned.join(', ');
export const TOTAL_DETECTOR_LABEL = `${PRODUCT_FACTS.detectors.total} pure Rust detectors`;
export const GRAPH_LANGUAGE_LABEL = `${PRODUCT_FACTS.languages.full_graph_count} graph-native languages`;
export const TOTAL_LANGUAGE_LABEL = `${PRODUCT_FACTS.languages.total_supported_count} languages total`;
