//! Quality detectors — code smells, complexity, naming, style, dead code.

mod boolean_trap;
mod commented_code;
mod data_clumps;
mod dead_code;
mod dead_store;
mod debug_code;
mod deep_nesting;
mod duplicate_code;
mod feature_envy;
mod god_class;
mod hardcoded_timeout;
mod inappropriate_intimacy;
mod inconsistent_returns;
mod influential_code;
mod large_files;
mod lazy_class;
mod long_methods;
mod long_parameter;
mod magic_numbers;
mod message_chain;
mod middle_man;
mod missing_docstrings;
mod refused_bequest;
mod single_char_names;
mod test_in_production;
mod todo_scanner;
mod unused_imports;

pub use boolean_trap::BooleanTrapDetector;
pub use commented_code::CommentedCodeDetector;
pub use data_clumps::DataClumpsDetector;
pub use dead_code::DeadCodeDetector;
pub use dead_store::DeadStoreDetector;
pub use debug_code::DebugCodeDetector;
pub use deep_nesting::DeepNestingDetector;
pub use duplicate_code::DuplicateCodeDetector;
pub use feature_envy::FeatureEnvyDetector;
pub use god_class::{GodClassDetector, GodClassThresholds};
pub use hardcoded_timeout::HardcodedTimeoutDetector;
pub use inappropriate_intimacy::InappropriateIntimacyDetector;
pub use inconsistent_returns::InconsistentReturnsDetector;
pub use influential_code::InfluentialCodeDetector;
pub use large_files::LargeFilesDetector;
pub use lazy_class::LazyClassDetector;
pub use long_methods::LongMethodsDetector;
pub use long_parameter::{LongParameterListDetector, LongParameterThresholds};
pub use magic_numbers::MagicNumbersDetector;
pub use message_chain::MessageChainDetector;
pub use middle_man::MiddleManDetector;
pub use missing_docstrings::MissingDocstringsDetector;
pub use refused_bequest::RefusedBequestDetector;
pub use single_char_names::SingleCharNamesDetector;
pub use test_in_production::TestInProductionDetector;
pub use todo_scanner::TodoScanner;
pub use unused_imports::UnusedImportsDetector;
