#!/usr/bin/env python3
"""Generate canonical product facts from source code.

This script exists to stop marketing and docs drift around detector counts and
language support. It derives the facts that can be computed from code, emits
machine-readable artifacts for the web app, and can validate that generated
files are current.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
DETECTORS_MOD = REPO_ROOT / "repotoire-cli" / "src" / "detectors" / "mod.rs"
PARSERS_MOD = REPO_ROOT / "repotoire-cli" / "src" / "parsers" / "mod.rs"
JSON_OUTPUT = REPO_ROOT / "product-facts.json"
TS_OUTPUT = REPO_ROOT / "repotoire" / "web" / "src" / "lib" / "product-facts.generated.ts"

# Regex-scanned languages are currently supported by detector/file-extension
# coverage but do not have full tree-sitter graph parsing.
REGEX_SCANNED_LANGUAGES = ["Ruby", "PHP", "Kotlin", "Swift"]


def count_registered_detectors(detectors_mod: str, const_name: str) -> int:
    match = re.search(rf"{const_name}: .*?= &\[(.*?)\];", detectors_mod, re.S)
    if not match:
        raise RuntimeError(f"Could not find {const_name} in detectors/mod.rs")
    return len(re.findall(r"register::<[^>]+>\(\)", match.group(1)))


def derive_full_graph_languages(parsers_mod: str) -> list[str]:
    body_match = re.search(r"let \(mut parsed, tree\) = match ext \{(.*?)// Unknown extension", parsers_mod, re.S)
    if not body_match:
        raise RuntimeError("Could not find parse_file_inner match body in parsers/mod.rs")

    body = body_match.group(1)
    languages: list[str] = []

    # Order matters for docs and marketing copy.
    candidates = [
        ("Python", r'"py" \| "pyi" =>'),
        ("TypeScript", r'"ts" \| "tsx" \| "js" \| "jsx" \| "mjs" \| "cjs" =>'),
        ("JavaScript", r'"ts" \| "tsx" \| "js" \| "jsx" \| "mjs" \| "cjs" =>'),
        ("Rust", r'"rs" =>'),
        ("Go", r'"go" =>'),
        ("Java", r'"java" =>'),
        ("C#", r'"cs" =>'),
        ("C", r'"c" =>'),
        ("C++", r'"cpp" \| "cc" \| "cxx" \| "c\+\+" \| "hpp" \| "hh" \| "hxx" \| "h\+\+" =>'),
    ]

    for language, pattern in candidates:
        if re.search(pattern, body):
            languages.append(language)

    return languages


def build_facts() -> dict[str, object]:
    detectors_mod = DETECTORS_MOD.read_text()
    parsers_mod = PARSERS_MOD.read_text()

    default_detectors = count_registered_detectors(detectors_mod, "DEFAULT_DETECTOR_FACTORIES")
    deep_detectors = count_registered_detectors(detectors_mod, "DEEP_ONLY_DETECTOR_FACTORIES")
    full_graph_languages = derive_full_graph_languages(parsers_mod)

    facts = {
        "detectors": {
            "default": default_detectors,
            "deep_scan": deep_detectors,
            "total": default_detectors + deep_detectors,
        },
        "languages": {
            "full_graph": full_graph_languages,
            "full_graph_count": len(full_graph_languages),
            "regex_scanned": REGEX_SCANNED_LANGUAGES,
            "regex_scanned_count": len(REGEX_SCANNED_LANGUAGES),
            "total_supported_count": len(full_graph_languages) + len(REGEX_SCANNED_LANGUAGES),
        },
        "messaging": {
            "headline_detector_count": default_detectors + deep_detectors,
            "headline_language_count": len(full_graph_languages),
            "headline_language_label": "graph-native languages",
        },
    }
    return facts


def render_typescript(facts: dict[str, object]) -> str:
    payload = json.dumps(facts, indent=2)
    return (
        "// This file is generated by scripts/product_facts.py. Do not edit by hand.\n"
        f"export const PRODUCT_FACTS = {payload} as const;\n\n"
        "export const FULL_GRAPH_LANGUAGE_LIST = PRODUCT_FACTS.languages.full_graph.join(', ');\n"
        "export const REGEX_SCANNED_LANGUAGE_LIST = PRODUCT_FACTS.languages.regex_scanned.join(', ');\n"
        "export const TOTAL_DETECTOR_LABEL = `${PRODUCT_FACTS.detectors.total} pure Rust detectors`;\n"
        "export const GRAPH_LANGUAGE_LABEL = `${PRODUCT_FACTS.languages.full_graph_count} graph-native languages`;\n"
        "export const TOTAL_LANGUAGE_LABEL = `${PRODUCT_FACTS.languages.total_supported_count} languages total`;\n"
    )


def write_if_changed(path: Path, content: str) -> bool:
    current = path.read_text() if path.exists() else None
    if current == content:
        return False
    path.write_text(content)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated artifacts are out of date")
    args = parser.parse_args()

    facts = build_facts()
    json_content = json.dumps(facts, indent=2) + "\n"
    ts_content = render_typescript(facts)

    if args.check:
        expected_json = JSON_OUTPUT.exists() and JSON_OUTPUT.read_text() == json_content
        expected_ts = TS_OUTPUT.exists() and TS_OUTPUT.read_text() == ts_content
        if expected_json and expected_ts:
            return 0
        if not expected_json:
            print(f"Out of date: {JSON_OUTPUT}", file=sys.stderr)
        if not expected_ts:
            print(f"Out of date: {TS_OUTPUT}", file=sys.stderr)
        return 1

    JSON_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    write_if_changed(JSON_OUTPUT, json_content)
    write_if_changed(TS_OUTPUT, ts_content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
